run:
  timeout: 2m

linters:
  enable:
    - asciicheck
    - bodyclose
    - contextcheck
    - deadcode
    - dogsled
    - durationcheck
    - dupl
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - gocritic
    - gofumpt
    - goimports
    - gomnd
    - gomoddirectives
    - gosimple
    - govet
    - ifshort
    - ineffassign
    - importas
    - misspell
    - noctx
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - wrapcheck

linters-settings:
  unparam:
    check-exported: false
  unused:
    check-exported: false
  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - status.Error(
      - retry.Recoverable(
      - retry.Unrecoverable(

modules-download-mode: readonly
