// Code generated by MockGen. DO NOT EDIT.
// Source: internal/genproto/mux_grpc.pb.go

// Package mockproto is a generated GoMock package.
package mockproto

import (
	context "context"
	reflect "reflect"

	genproto "github.com/bbralion/CTFloodBot/internal/genproto"
	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
	metadata "google.golang.org/grpc/metadata"
)

// MockMultiplexerServiceClient is a mock of MultiplexerServiceClient interface.
type MockMultiplexerServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockMultiplexerServiceClientMockRecorder
}

// MockMultiplexerServiceClientMockRecorder is the mock recorder for MockMultiplexerServiceClient.
type MockMultiplexerServiceClientMockRecorder struct {
	mock *MockMultiplexerServiceClient
}

// NewMockMultiplexerServiceClient creates a new mock instance.
func NewMockMultiplexerServiceClient(ctrl *gomock.Controller) *MockMultiplexerServiceClient {
	mock := &MockMultiplexerServiceClient{ctrl: ctrl}
	mock.recorder = &MockMultiplexerServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMultiplexerServiceClient) EXPECT() *MockMultiplexerServiceClientMockRecorder {
	return m.recorder
}

// GetConfig mocks base method.
func (m *MockMultiplexerServiceClient) GetConfig(ctx context.Context, in *genproto.ConfigRequest, opts ...grpc.CallOption) (*genproto.ConfigResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetConfig", varargs...)
	ret0, _ := ret[0].(*genproto.ConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockMultiplexerServiceClientMockRecorder) GetConfig(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockMultiplexerServiceClient)(nil).GetConfig), varargs...)
}

// RegisterHandler mocks base method.
func (m *MockMultiplexerServiceClient) RegisterHandler(ctx context.Context, in *genproto.RegisterRequest, opts ...grpc.CallOption) (genproto.MultiplexerService_RegisterHandlerClient, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RegisterHandler", varargs...)
	ret0, _ := ret[0].(genproto.MultiplexerService_RegisterHandlerClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterHandler indicates an expected call of RegisterHandler.
func (mr *MockMultiplexerServiceClientMockRecorder) RegisterHandler(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterHandler", reflect.TypeOf((*MockMultiplexerServiceClient)(nil).RegisterHandler), varargs...)
}

// MockMultiplexerService_RegisterHandlerClient is a mock of MultiplexerService_RegisterHandlerClient interface.
type MockMultiplexerService_RegisterHandlerClient struct {
	ctrl     *gomock.Controller
	recorder *MockMultiplexerService_RegisterHandlerClientMockRecorder
}

// MockMultiplexerService_RegisterHandlerClientMockRecorder is the mock recorder for MockMultiplexerService_RegisterHandlerClient.
type MockMultiplexerService_RegisterHandlerClientMockRecorder struct {
	mock *MockMultiplexerService_RegisterHandlerClient
}

// NewMockMultiplexerService_RegisterHandlerClient creates a new mock instance.
func NewMockMultiplexerService_RegisterHandlerClient(ctrl *gomock.Controller) *MockMultiplexerService_RegisterHandlerClient {
	mock := &MockMultiplexerService_RegisterHandlerClient{ctrl: ctrl}
	mock.recorder = &MockMultiplexerService_RegisterHandlerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMultiplexerService_RegisterHandlerClient) EXPECT() *MockMultiplexerService_RegisterHandlerClientMockRecorder {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockMultiplexerService_RegisterHandlerClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockMultiplexerService_RegisterHandlerClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockMultiplexerService_RegisterHandlerClient)(nil).CloseSend))
}

// Context mocks base method.
func (m *MockMultiplexerService_RegisterHandlerClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockMultiplexerService_RegisterHandlerClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockMultiplexerService_RegisterHandlerClient)(nil).Context))
}

// Header mocks base method.
func (m *MockMultiplexerService_RegisterHandlerClient) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockMultiplexerService_RegisterHandlerClientMockRecorder) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockMultiplexerService_RegisterHandlerClient)(nil).Header))
}

// Recv mocks base method.
func (m *MockMultiplexerService_RegisterHandlerClient) Recv() (*genproto.Update, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*genproto.Update)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockMultiplexerService_RegisterHandlerClientMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockMultiplexerService_RegisterHandlerClient)(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockMultiplexerService_RegisterHandlerClient) RecvMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockMultiplexerService_RegisterHandlerClientMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockMultiplexerService_RegisterHandlerClient)(nil).RecvMsg), m)
}

// SendMsg mocks base method.
func (m_2 *MockMultiplexerService_RegisterHandlerClient) SendMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockMultiplexerService_RegisterHandlerClientMockRecorder) SendMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockMultiplexerService_RegisterHandlerClient)(nil).SendMsg), m)
}

// Trailer mocks base method.
func (m *MockMultiplexerService_RegisterHandlerClient) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockMultiplexerService_RegisterHandlerClientMockRecorder) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockMultiplexerService_RegisterHandlerClient)(nil).Trailer))
}

// MockMultiplexerServiceServer is a mock of MultiplexerServiceServer interface.
type MockMultiplexerServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockMultiplexerServiceServerMockRecorder
}

// MockMultiplexerServiceServerMockRecorder is the mock recorder for MockMultiplexerServiceServer.
type MockMultiplexerServiceServerMockRecorder struct {
	mock *MockMultiplexerServiceServer
}

// NewMockMultiplexerServiceServer creates a new mock instance.
func NewMockMultiplexerServiceServer(ctrl *gomock.Controller) *MockMultiplexerServiceServer {
	mock := &MockMultiplexerServiceServer{ctrl: ctrl}
	mock.recorder = &MockMultiplexerServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMultiplexerServiceServer) EXPECT() *MockMultiplexerServiceServerMockRecorder {
	return m.recorder
}

// GetConfig mocks base method.
func (m *MockMultiplexerServiceServer) GetConfig(arg0 context.Context, arg1 *genproto.ConfigRequest) (*genproto.ConfigResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig", arg0, arg1)
	ret0, _ := ret[0].(*genproto.ConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockMultiplexerServiceServerMockRecorder) GetConfig(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockMultiplexerServiceServer)(nil).GetConfig), arg0, arg1)
}

// RegisterHandler mocks base method.
func (m *MockMultiplexerServiceServer) RegisterHandler(arg0 *genproto.RegisterRequest, arg1 genproto.MultiplexerService_RegisterHandlerServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterHandler", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterHandler indicates an expected call of RegisterHandler.
func (mr *MockMultiplexerServiceServerMockRecorder) RegisterHandler(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterHandler", reflect.TypeOf((*MockMultiplexerServiceServer)(nil).RegisterHandler), arg0, arg1)
}

// mustEmbedUnimplementedMultiplexerServiceServer mocks base method.
func (m *MockMultiplexerServiceServer) mustEmbedUnimplementedMultiplexerServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedMultiplexerServiceServer")
}

// mustEmbedUnimplementedMultiplexerServiceServer indicates an expected call of mustEmbedUnimplementedMultiplexerServiceServer.
func (mr *MockMultiplexerServiceServerMockRecorder) mustEmbedUnimplementedMultiplexerServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedMultiplexerServiceServer", reflect.TypeOf((*MockMultiplexerServiceServer)(nil).mustEmbedUnimplementedMultiplexerServiceServer))
}

// MockUnsafeMultiplexerServiceServer is a mock of UnsafeMultiplexerServiceServer interface.
type MockUnsafeMultiplexerServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeMultiplexerServiceServerMockRecorder
}

// MockUnsafeMultiplexerServiceServerMockRecorder is the mock recorder for MockUnsafeMultiplexerServiceServer.
type MockUnsafeMultiplexerServiceServerMockRecorder struct {
	mock *MockUnsafeMultiplexerServiceServer
}

// NewMockUnsafeMultiplexerServiceServer creates a new mock instance.
func NewMockUnsafeMultiplexerServiceServer(ctrl *gomock.Controller) *MockUnsafeMultiplexerServiceServer {
	mock := &MockUnsafeMultiplexerServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeMultiplexerServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeMultiplexerServiceServer) EXPECT() *MockUnsafeMultiplexerServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedMultiplexerServiceServer mocks base method.
func (m *MockUnsafeMultiplexerServiceServer) mustEmbedUnimplementedMultiplexerServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedMultiplexerServiceServer")
}

// mustEmbedUnimplementedMultiplexerServiceServer indicates an expected call of mustEmbedUnimplementedMultiplexerServiceServer.
func (mr *MockUnsafeMultiplexerServiceServerMockRecorder) mustEmbedUnimplementedMultiplexerServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedMultiplexerServiceServer", reflect.TypeOf((*MockUnsafeMultiplexerServiceServer)(nil).mustEmbedUnimplementedMultiplexerServiceServer))
}

// MockMultiplexerService_RegisterHandlerServer is a mock of MultiplexerService_RegisterHandlerServer interface.
type MockMultiplexerService_RegisterHandlerServer struct {
	ctrl     *gomock.Controller
	recorder *MockMultiplexerService_RegisterHandlerServerMockRecorder
}

// MockMultiplexerService_RegisterHandlerServerMockRecorder is the mock recorder for MockMultiplexerService_RegisterHandlerServer.
type MockMultiplexerService_RegisterHandlerServerMockRecorder struct {
	mock *MockMultiplexerService_RegisterHandlerServer
}

// NewMockMultiplexerService_RegisterHandlerServer creates a new mock instance.
func NewMockMultiplexerService_RegisterHandlerServer(ctrl *gomock.Controller) *MockMultiplexerService_RegisterHandlerServer {
	mock := &MockMultiplexerService_RegisterHandlerServer{ctrl: ctrl}
	mock.recorder = &MockMultiplexerService_RegisterHandlerServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMultiplexerService_RegisterHandlerServer) EXPECT() *MockMultiplexerService_RegisterHandlerServerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockMultiplexerService_RegisterHandlerServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockMultiplexerService_RegisterHandlerServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockMultiplexerService_RegisterHandlerServer)(nil).Context))
}

// RecvMsg mocks base method.
func (m_2 *MockMultiplexerService_RegisterHandlerServer) RecvMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockMultiplexerService_RegisterHandlerServerMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockMultiplexerService_RegisterHandlerServer)(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockMultiplexerService_RegisterHandlerServer) Send(arg0 *genproto.Update) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockMultiplexerService_RegisterHandlerServerMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockMultiplexerService_RegisterHandlerServer)(nil).Send), arg0)
}

// SendHeader mocks base method.
func (m *MockMultiplexerService_RegisterHandlerServer) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockMultiplexerService_RegisterHandlerServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockMultiplexerService_RegisterHandlerServer)(nil).SendHeader), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockMultiplexerService_RegisterHandlerServer) SendMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockMultiplexerService_RegisterHandlerServerMockRecorder) SendMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockMultiplexerService_RegisterHandlerServer)(nil).SendMsg), m)
}

// SetHeader mocks base method.
func (m *MockMultiplexerService_RegisterHandlerServer) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockMultiplexerService_RegisterHandlerServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockMultiplexerService_RegisterHandlerServer)(nil).SetHeader), arg0)
}

// SetTrailer mocks base method.
func (m *MockMultiplexerService_RegisterHandlerServer) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockMultiplexerService_RegisterHandlerServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockMultiplexerService_RegisterHandlerServer)(nil).SetTrailer), arg0)
}
