name: lint
on:
  - pull_request
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
